// brief-generator.ts — Project Brief + Dev Agent Prompt generators
// Pure utility: no React, no side effects. Output is a markdown string.

import type { ProjectState } from "./project-state";

// ─── Project Brief ───────────────────────────────────────────────────────────

export function generateProjectBrief(params: {
  project: { name: string; idea?: string | null; stage?: string | null; created_at: string };
  state: ProjectState;
  tasks: Array<{ title: string; status: string; priority: string; category?: string | null }>;
  reports: Array<{ tool: string; score?: number | null; created_at: string; title: string }>;
  proofSignalCount?: number;
}): string {
  const { project, state, tasks, reports, proofSignalCount = 0 } = params;
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const lines: string[] = [];

  lines.push(`# Project Brief: ${project.name}`);
  lines.push(`*Generated ${today} · Phase: ${state.stage} · Readiness: ${state.readiness}%*`);
  lines.push("");

  lines.push("## Summary");
  lines.push(project.idea ?? "*No idea description provided.*");
  lines.push("");

  lines.push("## Current Phase");
  lines.push(`**${state.stage}** — ${state.readiness}% launch-ready`);
  lines.push("");

  const SCORE_MAP: Record<string, number> = {
    idea: state.ideaScore,
    reality: state.realityScore,
    proof: state.proofScore,
    swarm: state.swarmScore,
    mvp: state.mvpScore,
    doctor: state.doctorScore,
    launch: state.launchScore,
  };
  const scoreEntries = Object.entries(SCORE_MAP).filter(([, v]) => v > 0);
  if (scoreEntries.length > 0) {
    lines.push("## Intelligence Scores");
    for (const [tool, score] of scoreEntries) {
      const bar = "█".repeat(Math.round(score / 10)) + "░".repeat(10 - Math.round(score / 10));
      lines.push(`- **${tool.padEnd(8)}** ${bar} ${score}/100`);
    }
    lines.push("");
  }

  if (proofSignalCount > 0) {
    lines.push("## Proof State");
    lines.push(`${proofSignalCount} validation signal${proofSignalCount !== 1 ? "s" : ""} collected`);
    lines.push("");
  }

  if (state.topBlocker) {
    lines.push("## Top Blocker");
    lines.push(`> ⚠ ${state.topBlocker}`);
    lines.push("");
  }

  if (state.failedGates.length > 0) {
    lines.push("## Failed Launch Gates");
    for (const g of state.failedGates) lines.push(`- ✗ ${g}`);
    lines.push("");
  }

  const openTasks = tasks.filter((t) => t.status !== "completed");
  if (openTasks.length > 0) {
    lines.push("## Open Tasks");
    const highPrio = openTasks.filter((t) => t.priority === "high" || t.priority === "critical");
    const other = openTasks.filter((t) => t.priority !== "high" && t.priority !== "critical");
    for (const t of [...highPrio, ...other].slice(0, 12)) {
      lines.push(`- [${t.priority.toUpperCase()}] ${t.title}`);
    }
    if (openTasks.length > 12) lines.push(`*…and ${openTasks.length - 12} more open tasks*`);
    lines.push("");
  }

  lines.push("## Next Best Action");
  lines.push(`**${state.nextAction.title}**`);
  lines.push(`→ ${state.nextAction.href}`);
  lines.push(`*${state.nextAction.reason}*`);
  lines.push("");

  lines.push("## Recommended Next 7 Days");
  const sprint = openTasks.filter((t) => t.priority === "high" || t.priority === "critical").slice(0, 5);
  if (sprint.length > 0) {
    sprint.forEach((t, i) => lines.push(`${i + 1}. ${t.title}`));
  } else {
    lines.push(`1. ${state.nextAction.title}`);
    lines.push("2. Review and complete open tasks");
    lines.push("3. Re-run relevant intelligence tool after changes");
    lines.push("4. Check score trends for improvements");
    lines.push("5. Consult Product Twin for strategic synthesis");
  }
  lines.push("");

  if (reports.length > 0) {
    const latest = [...reports].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()).slice(0, 4);
    lines.push("## Recent Reports");
    for (const r of latest) {
      lines.push(`- ${r.title}${r.score != null ? ` (${r.score}/100)` : ""} — ${new Date(r.created_at).toLocaleDateString()}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by Noctra · ${today}*`);

  return lines.join("\n");
}

// ─── Dev Agent Prompt ────────────────────────────────────────────────────────

export function generateDevAgentPrompt(params: {
  project: { name: string; idea?: string | null };
  state: ProjectState;
  tasks: Array<{ title: string; status: string; priority: string; category?: string | null }>;
  doctorPayload?: unknown;
  mvpPayload?: unknown;
}): string {
  const { project, state, tasks, doctorPayload, mvpPayload } = params;
  const lines: string[] = [];

  const doc = doctorPayload as Record<string, unknown> | null;
  const docData = ((doc?.data ?? doc) ?? {}) as Record<string, unknown>;
  const mvp = mvpPayload as Record<string, unknown> | null;
  const mvpData = ((mvp?.data ?? mvp) ?? {}) as Record<string, unknown>;

  const gates = (docData.gates as Array<{ name: string; status: string; how_to_fix?: string; why?: string }> | undefined) ?? [];
  const redGates = gates.filter(g => g.status === "RED");
  const yellowGates = gates.filter(g => g.status === "YELLOW");
  const redGateNames = (docData.red_gates as string[] | undefined) ?? [];
  const evidence = (docData.evidence as Array<{ filePath: string; lineNumber?: number; explanation: string; severity: string; signal?: string }> | undefined) ?? [];
  const repairQueue = (docData.repair_queue as string[] | undefined) ?? [];
  const fixPlan = (docData.fix_plan as Array<{ title: string; priority: string; files?: string[]; acceptance_criteria?: string[] }> | undefined) ?? [];
  const docIssues = (docData.issues as Array<{ severity: string; issue: string; fix?: string; file?: string }> | undefined) ?? [];
  const criticalIssues = docIssues.filter((i) => i.severity === "CRITICAL" || i.severity === "HIGH").slice(0, 6);
  const securityFindings = (docData.security_findings as Array<{ finding: string; severity?: string; fix?: string }> | undefined) ?? [];
  const testingGaps = (docData.testing_gaps as string[] | undefined) ?? [];
  const deploymentGaps = (docData.deployment_gaps as string[] | undefined) ?? [];
  const alignment = docData.alignment as Record<string, unknown> | undefined;
  const missingReqs = (alignment?.missingProductRequirements as Array<{ title: string; description: string }> | undefined) ?? [];
  const allBlockers = [...new Set([...redGates.map(g => g.name), ...redGateNames])];

  const openHigh = tasks.filter((t) => t.status !== "completed" && (t.priority === "high" || t.priority === "critical"));

  lines.push(`# Next Build Prompt — ${project.name}`);
  lines.push("");
  lines.push("**Targets:** Codex · Replit Agent · Cursor · Windsurf · Cline");
  lines.push("**Purpose:** Fix all launch blockers, code risks, and gaps identified by Project Doctor");
  lines.push("");

  // 1. Project Context
  lines.push("## Project Context");
  lines.push(`**Project:** ${project.name}`);
  lines.push(`**Idea:** ${project.idea ?? "Not specified"}`);
  lines.push(`**Phase:** ${state.stage} · **Readiness:** ${state.readiness}%`);
  if (state.topBlocker) lines.push(`**Top Blocker:** ${state.topBlocker}`);
  lines.push("");

  // 2. Diagnosis Summary
  const healthScore = docData.health_score ?? docData.score ?? state.doctorScore ?? 0;
  const launchReadiness = docData.launch_readiness as string ?? (allBlockers.length === 0 ? "CONDITIONAL" : "NO-GO");
  lines.push("## Diagnosis Summary");
  lines.push(`- **Health Score:** ${healthScore}/100`);
  lines.push(`- **Launch Readiness:** ${launchReadiness}`);
  lines.push(`- **RED Gates:** ${allBlockers.length} · **YELLOW Gates:** ${yellowGates.length} · **GREEN Gates:** ${gates.filter(g => g.status === "GREEN").length}`);
  lines.push(`- **Critical Issues:** ${criticalIssues.length} · **Security Findings:** ${securityFindings.length}`);
  lines.push(`- **Evidence Findings:** ${evidence.length} · **Repair Items:** ${repairQueue.length + fixPlan.length}`);
  if (docData.summary) lines.push(`- **Summary:** ${docData.summary}`);
  lines.push("");

  // 3. Critical Blockers (RED gates)
  if (allBlockers.length > 0) {
    lines.push("## Critical Blockers (Must Fix Before Launch)");
    const allGates = [...redGates];
    redGateNames.forEach(name => {
      if (!allGates.some(g => g.name === name)) {
        allGates.push({ name, status: "RED", how_to_fix: "" });
      }
    });
    allGates.slice(0, 8).forEach((g, i) => {
      lines.push(`### ${i + 1}. ${g.name}`);
      if (g.how_to_fix) lines.push(`**Fix:** ${g.how_to_fix}`);
      if (g.why) lines.push(`**Why it matters:** ${g.why}`);
      lines.push("");
    });
  }

  // 4. Files Likely Affected
  if (evidence.length > 0) {
    lines.push("## Files Likely Affected");
    lines.push("| File | Issue | Severity |");
    lines.push("|------|-------|----------|");
    evidence.slice(0, 12).forEach(e => {
      const path = `\`${e.filePath}${e.lineNumber ? `:${e.lineNumber}` : ""}\``;
      lines.push(`| ${path} | ${e.explanation || e.signal} | ${e.severity} |`);
    });
    if (evidence.length > 12) lines.push(`| … and ${evidence.length - 12} more | | |`);
    lines.push("");
  }

  // Also include files from fix plan
  const fixPlanFiles = fixPlan.flatMap(f => f.files ?? []);
  if (fixPlanFiles.length > 0) {
    lines.push("### Files from Repair Plan");
    fixPlanFiles.slice(0, 10).forEach(f => lines.push(`- \`${f}\``));
    lines.push("");
  }

  // 5. Exact Requirements
  lines.push("## Exact Requirements");
  let reqNum = 1;
  if (allBlockers.length > 0) {
    lines.push(`${reqNum++}. Fix all RED launch gates: ${allBlockers.join(", ")}`);
  }
  if (criticalIssues.length > 0) {
    lines.push(`${reqNum++}. Resolve all CRITICAL/HIGH issues:`);
    criticalIssues.slice(0, 5).forEach(iss => {
      lines.push(`   - ${iss.issue}${iss.file ? ` (\`${iss.file}\`)` : ""}${iss.fix ? ` → ${iss.fix}` : ""}`);
    });
  }
  if (securityFindings.length > 0) {
    lines.push(`${reqNum++}. Fix security findings:`);
    securityFindings.slice(0, 4).forEach(s => {
      lines.push(`   - ${s.finding}${s.fix ? ` → ${s.fix}` : ""}`);
    });
  }
  if (repairQueue.length > 0) {
    lines.push(`${reqNum++}. Address repair queue items in order:`);
    repairQueue.slice(0, 6).forEach((item, i) => lines.push(`   ${i + 1}. ${item}`));
  }
  if (fixPlan.length > 0) {
    lines.push(`${reqNum++}. Execute fix plan:`);
    fixPlan.slice(0, 5).forEach(f => {
      const files = f.files?.length ? ` (${f.files.join(", ")})` : "";
      lines.push(`   - ${f.title}${files} [${f.priority}]`);
    });
  }
  if (testingGaps.length > 0) {
    lines.push(`${reqNum++}. Add tests for: ${testingGaps.slice(0, 3).join(", ")}`);
  }
  if (deploymentGaps.length > 0) {
    lines.push(`${reqNum++}. Fix deployment: ${deploymentGaps.slice(0, 3).join(", ")}`);
  }
  if (missingReqs.length > 0) {
    lines.push(`${reqNum++}. Implement missing product requirements:`);
    missingReqs.slice(0, 4).forEach(m => lines.push(`   - ${m.title}: ${m.description}`));
  }
  if (openHigh.length > 0) {
    lines.push(`${reqNum++}. Complete high-priority tasks:`);
    openHigh.slice(0, 5).forEach(t => lines.push(`   - [${t.priority.toUpperCase()}] ${t.title}`));
  }
  lines.push(`${reqNum++}. Ensure health score improves to 70+/100 on re-scan`);
  lines.push("");

  // 6. Do Not Break Rules
  lines.push("## Do Not Break Rules");
  lines.push("- Do NOT modify the project's overall architecture or framework");
  lines.push("- Do NOT change package.json dependencies unless explicitly required by a fix");
  lines.push("- Do NOT remove or break existing functionality");
  lines.push("- Do NOT add new features — this is a repair session only");
  lines.push("- Do NOT change database schemas or migration files");
  lines.push("- Preserve all existing API contracts and endpoint signatures");
  lines.push("- Do NOT modify authentication flows or session handling");
  lines.push("- Do NOT delete routes or navigation entries");
  lines.push("- Do NOT introduce new third-party services or APIs");
  lines.push("");

  // 7. Acceptance Criteria
  lines.push("## Acceptance Criteria");
  lines.push("- [ ] All RED launch gates resolved to GREEN or YELLOW");
  lines.push("- [ ] All CRITICAL and HIGH severity issues resolved");
  lines.push("- [ ] All security findings addressed");
  lines.push("- [ ] No new TypeScript errors introduced");
  lines.push("- [ ] No console.log or debugger statements remain in production code");
  lines.push("- [ ] All secrets moved to environment variables");
  lines.push("- [ ] Each change is minimal, focused, and verified");
  lines.push("- [ ] Existing features work correctly after each change");
  lines.push("- [ ] Health score improves to 70+ on re-scan");
  lines.push("");

  // 8. Test Commands
  lines.push("## Test Commands");
  lines.push("```bash");
  lines.push("# TypeScript check");
  lines.push("pnpm run typecheck");
  lines.push("");
  lines.push("# Build verification");
  lines.push("pnpm run build");
  lines.push("");
  lines.push("# Run tests if configured");
  lines.push("pnpm run test");
  lines.push("```");
  lines.push("");

  // 9. Security Reminders
  lines.push("## Security Reminders");
  lines.push("- Never commit .env files or real secrets to version control");
  lines.push("- Never use eval() or new Function() in production code");
  lines.push("- Never expose API keys, tokens, or credentials in client-side code");
  lines.push("- Always validate and sanitize user input on the server side");
  lines.push("- Use parameterized queries for database operations");
  lines.push("- Set secure, HttpOnly, SameSite cookies for sessions");
  lines.push("");

  // 10. Build / Typecheck Instructions
  lines.push("## Build / Typecheck Instructions");
  lines.push("1. Run `pnpm run typecheck` after each batch of changes");
  lines.push("2. Fix all TypeScript errors before proceeding to the next batch");
  lines.push("3. Run `pnpm run build` to verify the build succeeds");
  lines.push("4. Manually test each fixed feature in the browser");
  lines.push("5. Re-upload the project ZIP to Project Doctor to confirm health score improvement");
  lines.push("6. Verify no regressions in existing features");
  lines.push("7. If all gates pass, proceed to launch");
  lines.push("");

  // 11. Expected Outcome
  lines.push("## Expected Outcome");
  lines.push(`- Health score improves from ${healthScore}/100 to 70+/100`);
  lines.push("- All launch gates pass (GREEN or YELLOW)");
  lines.push("- Codebase is production-ready with zero critical/high severity issues");
  lines.push("- All security vulnerabilities are fixed");
  lines.push("- Tests exist for critical paths");
  lines.push("- Deployment configuration is complete");
  lines.push("- Missing product requirements are implemented");
  lines.push("- Project can be deployed without manual intervention");
  lines.push("");

  lines.push("---");
  lines.push("*Generated by Noctra*");
  lines.push("*Project Doctor — Next Build Prompt*");

  return lines.join("\n");
}
