// brief-generator.ts — Project Brief + Dev Agent Prompt generators
// Pure utility: no React, no side effects. Output is a markdown string.

import type { ProjectState } from "./project-state";

// ─── Project Brief ───────────────────────────────────────────────────────────

export function generateProjectBrief(params: {
  project: { name: string; idea?: string | null; stage?: string | null; created_at: string };
  state: ProjectState;
  tasks: Array<{ title: string; status: string; priority: string; category?: string | null }>;
  reports: Array<{ tool: string; score?: number | null; created_at: string; title: string }>;
  proofSignalCount?: number;
}): string {
  const { project, state, tasks, reports, proofSignalCount = 0 } = params;
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const lines: string[] = [];

  lines.push(`# Project Brief: ${project.name}`);
  lines.push(`*Generated ${today} · Phase: ${state.phase} · Readiness: ${state.readiness}%*`);
  lines.push("");

  lines.push("## Summary");
  lines.push(project.idea ?? "*No idea description provided.*");
  lines.push("");

  lines.push("## Current Phase");
  lines.push(`**${state.phase}** — ${state.readiness}% launch-ready`);
  lines.push("");

  const SCORE_MAP: Record<string, number> = {
    idea: state.ideaScore,
    reality: state.realityScore,
    proof: state.proofScore,
    swarm: state.swarmScore,
    mvp: state.mvpScore,
    doctor: state.doctorScore,
    launch: state.launchScore,
  };
  const scoreEntries = Object.entries(SCORE_MAP).filter(([, v]) => v > 0);
  if (scoreEntries.length > 0) {
    lines.push("## Intelligence Scores");
    for (const [tool, score] of scoreEntries) {
      const bar = "█".repeat(Math.round(score / 10)) + "░".repeat(10 - Math.round(score / 10));
      lines.push(`- **${tool.padEnd(8)}** ${bar} ${score}/100`);
    }
    lines.push("");
  }

  if (proofSignalCount > 0) {
    lines.push("## Proof State");
    lines.push(`${proofSignalCount} validation signal${proofSignalCount !== 1 ? "s" : ""} collected`);
    lines.push("");
  }

  if (state.topBlocker) {
    lines.push("## Top Blocker");
    lines.push(`> ⚠ ${state.topBlocker}`);
    lines.push("");
  }

  if (state.failedGates.length > 0) {
    lines.push("## Failed Launch Gates");
    for (const g of state.failedGates) lines.push(`- ✗ ${g}`);
    lines.push("");
  }

  const openTasks = tasks.filter((t) => t.status !== "completed");
  if (openTasks.length > 0) {
    lines.push("## Open Tasks");
    const highPrio = openTasks.filter((t) => t.priority === "high" || t.priority === "critical");
    const other = openTasks.filter((t) => t.priority !== "high" && t.priority !== "critical");
    for (const t of [...highPrio, ...other].slice(0, 12)) {
      lines.push(`- [${t.priority.toUpperCase()}] ${t.title}`);
    }
    if (openTasks.length > 12) lines.push(`*…and ${openTasks.length - 12} more open tasks*`);
    lines.push("");
  }

  lines.push("## Next Best Action");
  lines.push(`**${state.nextAction.title}**`);
  lines.push(`→ ${state.nextAction.href}`);
  lines.push(`*${state.nextAction.reason}*`);
  lines.push("");

  lines.push("## Recommended Next 7 Days");
  const sprint = openTasks.filter((t) => t.priority === "high" || t.priority === "critical").slice(0, 5);
  if (sprint.length > 0) {
    sprint.forEach((t, i) => lines.push(`${i + 1}. ${t.title}`));
  } else {
    lines.push(`1. ${state.nextAction.title}`);
    lines.push("2. Review and complete open tasks");
    lines.push("3. Re-run relevant intelligence tool after changes");
    lines.push("4. Check score trends for improvements");
    lines.push("5. Consult Product Twin for strategic synthesis");
  }
  lines.push("");

  if (reports.length > 0) {
    const latest = [...reports].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()).slice(0, 4);
    lines.push("## Recent Reports");
    for (const r of latest) {
      lines.push(`- ${r.title}${r.score != null ? ` (${r.score}/100)` : ""} — ${new Date(r.created_at).toLocaleDateString()}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by Noctra — Developer Intelligence OS · ${today}*`);

  return lines.join("\n");
}

// ─── Dev Agent Prompt ────────────────────────────────────────────────────────

export function generateDevAgentPrompt(params: {
  project: { name: string; idea?: string | null };
  state: ProjectState;
  tasks: Array<{ title: string; status: string; priority: string; category?: string | null }>;
  doctorPayload?: unknown;
  mvpPayload?: unknown;
}): string {
  const { project, state, tasks, doctorPayload, mvpPayload } = params;
  const lines: string[] = [];

  const doc = doctorPayload as Record<string, unknown> | null;
  const docData = ((doc?.data ?? doc) ?? {}) as Record<string, unknown>;
  const mvp = mvpPayload as Record<string, unknown> | null;
  const mvpData = ((mvp?.data ?? mvp) ?? {}) as Record<string, unknown>;

  lines.push(`## Next Build Prompt — ${project.name}`);
  lines.push("*Paste into Replit Agent, Cursor, or Windsurf*");
  lines.push("");

  lines.push("### Context");
  lines.push(`**Project:** ${project.name}`);
  lines.push(`**Idea:** ${project.idea ?? "Not specified"}`);
  lines.push(`**Current Phase:** ${state.phase}`);
  lines.push(`**Readiness:** ${state.readiness}%`);
  if (state.topBlocker) lines.push(`**Top Blocker:** ${state.topBlocker}`);
  lines.push("");

  lines.push("### Goal");
  lines.push(state.nextAction.title);
  if (state.nextAction.description) lines.push("");
  if (state.nextAction.description) lines.push(state.nextAction.description);
  lines.push("");

  if (state.failedGates.length > 0) {
    lines.push("### Failed Launch Gates (fix these first)");
    for (const g of state.failedGates) lines.push(`- ${g}`);
    lines.push("");
  }

  const openHigh = tasks.filter((t) => t.status !== "completed" && (t.priority === "high" || t.priority === "critical"));
  if (openHigh.length > 0) {
    lines.push("### High-Priority Requirements");
    for (const t of openHigh.slice(0, 8)) lines.push(`- [${t.priority.toUpperCase()}] ${t.title}`);
    lines.push("");
  }

  const repairQueue = (docData.repair_queue as string[] | undefined) ?? [];
  if (repairQueue.length > 0) {
    lines.push("### Doctor Repair Queue");
    repairQueue.slice(0, 6).forEach((item, i) => lines.push(`${i + 1}. ${item}`));
    lines.push("");
  }

  const docIssues = (docData.issues as Array<{ severity: string; issue: string; fix?: string }> | undefined) ?? [];
  const criticalIssues = docIssues.filter((i) => i.severity === "CRITICAL" || i.severity === "HIGH").slice(0, 4);
  if (criticalIssues.length > 0) {
    lines.push("### Critical Issues from Project Doctor");
    for (const issue of criticalIssues) {
      lines.push(`- **[${issue.severity}]** ${issue.issue}${issue.fix ? ` → Fix: ${issue.fix}` : ""}`);
    }
    lines.push("");
  }

  const arch = mvpData.architecture as string | undefined;
  if (arch) {
    lines.push("### MVP Architecture Decisions");
    lines.push(arch);
    lines.push("");
  }

  const mvpFeatures = (mvpData.features ?? mvpData.core_features) as Array<{ feature: string; priority?: string }> | undefined;
  if (mvpFeatures && mvpFeatures.length > 0) {
    lines.push("### Files Likely Affected");
    lines.push("Based on MVP feature scope:");
    for (const f of mvpFeatures.slice(0, 5)) {
      lines.push(`- Feature: ${typeof f === "string" ? f : f.feature}`);
    }
    lines.push("");
  }

  lines.push("### Do Not Break");
  lines.push("- Existing authentication flows and session handling");
  lines.push("- Database schema and all existing data");
  lines.push("- Current API contracts (no breaking endpoint changes)");
  lines.push("- TypeScript build — must pass `tsc --noEmit` with 0 errors");
  lines.push("- Existing routes and navigation");
  lines.push("");

  lines.push("### Acceptance Criteria");
  lines.push(`- All ${state.failedGates.length || "previously"} failed launch gates resolved`);
  lines.push("- No new TypeScript errors introduced");
  lines.push("- High-priority tasks addressed and verifiable");
  lines.push("- Each change has a clear manual verification step");
  lines.push("");

  lines.push("### Testing Instructions");
  lines.push("1. Run `pnpm run typecheck` — must pass with 0 errors");
  lines.push("2. Verify each fixed gate/issue manually in the browser");
  lines.push("3. Re-upload project ZIP to Project Doctor to confirm health score improvement");
  lines.push("4. Check no existing features are broken");
  lines.push("");

  lines.push("---");
  lines.push("*Generated by Noctra — Developer Intelligence OS*");

  return lines.join("\n");
}
