export function exportReportPDF(report: {
  title: string;
  tool: string;
  score?: number | null;
  summary?: string | null;
  markdown?: string;
  created_at: string;
}) {
  const win = window.open("", "_blank");
  if (!win) return;

  const scoreColor = report.score == null ? "#4a5268" : report.score >= 70 ? "#34d399" : report.score >= 40 ? "#f59e0b" : "#f43f5e";
  const toolLabel = report.tool.charAt(0).toUpperCase() + report.tool.slice(1);

  win.document.write(`
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${report.title} — DEVULTIMATE Report</title>
  <style>
    @page { margin: 2cm; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 11pt; line-height: 1.6; color: #1a1a2e; padding: 0;
    }
    .header {
      border-bottom: 3px solid ${scoreColor};
      padding-bottom: 1.5rem; margin-bottom: 2rem;
      display: flex; justify-content: space-between; align-items: flex-start;
    }
    .header h1 { font-size: 18pt; font-weight: 700; margin: 0 0 0.3rem 0; }
    .header .meta { font-size: 9pt; color: #666; }
    .score-badge {
      background: ${scoreColor}; color: #fff; padding: 0.5rem 1rem;
      border-radius: 6px; text-align: center; min-width: 80px;
    }
    .score-badge .number { font-size: 22pt; font-weight: 800; display: block; }
    .score-badge .label { font-size: 7pt; text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.9; }
    .summary { background: #f5f5f5; padding: 1rem; border-radius: 6px; margin-bottom: 2rem; font-size: 10pt; color: #444; }
    .section { margin-bottom: 1.5rem; }
    .section h2 { font-size: 13pt; font-weight: 600; margin-bottom: 0.5rem; color: ${scoreColor}; }
    .section p, .section li { font-size: 10pt; color: #333; margin-bottom: 0.3rem; }
    .section ul { padding-left: 1.5rem; }
    pre {
      background: #f5f5f5; border: 1px solid #ddd; border-radius: 4px;
      padding: 0.75rem; font-size: 8pt; overflow-x: auto;
      font-family: 'SF Mono', 'Fira Code', monospace;
    }
    code { font-family: 'SF Mono', 'Fira Code', monospace; font-size: 9pt; }
    .footer {
      margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd;
      font-size: 8pt; color: #999; text-align: center;
    }
    table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; }
    th, td { border: 1px solid #ddd; padding: 0.4rem 0.6rem; text-align: left; font-size: 9pt; }
    th { background: #f5f5f5; font-weight: 600; }
    @media print {
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="no-print" style="text-align:center;margin-bottom:2rem;padding:0.5rem;background:#f0f0f0;border-radius:4px;font-size:9pt;">
    Click print or press Ctrl+P to save as PDF
    <button onclick="window.print()" style="margin-left:1rem;padding:0.25rem 0.75rem;cursor:pointer;">Print / Save PDF</button>
  </div>

  <div class="header">
    <div>
      <h1>${esc(report.title)}</h1>
      <div class="meta">
        ${esc(toolLabel)} · ${new Date(report.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
      </div>
    </div>
    ${report.score != null ? `<div class="score-badge"><span class="number">${report.score}</span><span class="label">/ 100</span></div>` : ""}
  </div>

  ${report.summary ? `<div class="summary">${esc(report.summary)}</div>` : ""}

  <div class="section">
    ${renderMarkdownToHTML(report.markdown || "")}
  </div>

  <div class="footer">
    Generated by DEVULTIMATE — Launch Readiness Platform<br>
    ${new Date().toLocaleString()}
  </div>

  <script>
    setTimeout(() => window.print(), 500);
  </script>
</body>
</html>
  `);

  win.document.close();
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function renderMarkdownToHTML(md: string): string {
  const lines = md.split("\n");
  let html = "";
  let inList = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;

    if (line.startsWith("# ")) {
      if (inList) { html += "</ul>"; inList = false; }
      html += `<h2>${esc(line.slice(2))}</h2>`;
    } else if (line.startsWith("## ")) {
      if (inList) { html += "</ul>"; inList = false; }
      html += `<h3>${esc(line.slice(3))}</h3>`;
    } else if (line.startsWith("### ")) {
      if (inList) { html += "</ul>"; inList = false; }
      html += `<h4>${esc(line.slice(4))}</h4>`;
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      if (!inList) { html += "<ul>"; inList = true; }
      html += `<li>${esc(line.slice(2))}</li>`;
    } else if (line.match(/^\d+\.\s/)) {
      if (!inList) { html += "<ol>"; inList = true; }
      html += `<li>${esc(line.replace(/^\d+\.\s/, ""))}</li>`;
    } else if (line.trim() === "") {
      if (inList) { html += "</ul>"; inList = false; }
      html += "<br/>";
    } else if (line.startsWith("|")) {
      if (line.includes("---")) continue;
      const cells = line.split("|").filter(Boolean).map((c) => esc(c.trim()));
      html += `<tr>${cells.map((c) => `<td>${c}</td>`).join("")}</tr>`;
    } else {
      if (inList) { html += "</ul>"; inList = false; }
      html += `<p>${esc(line)}</p>`;
    }
  }
  if (inList) html += "</ul>";

  return html;
}
